public enum TileType
{
    Empty,
    AllNeighboured,
    LeftBotRightNeighboured,
    TopLeftBotNeighboured,
    RightTopLeftNeighboured,
    BotRightTopNeighboured,
    VerticalNeighboured,
    HorizontalNeighboured,
    TopRightNeighboured,
    RightBotNeighboured,
    BotLeftNeighboured,
    LeftTopNeighboured,
    LeftNeighboured,
    BotNeighboured,
    RightNeighboured,
    TopNeighboured,
    NotNeighboured
}
