on: push

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: c-hive/gha-remove-artifacts@v1.2.0
        with:
          age: '0 ms'
          skip-tags: false
      - uses: actions/checkout@v2.3.4
      - uses: actions/cache@v2.1.3
        with:
          path: Unity/Library
          key: Library-TheWall-StandaloneWindows64
      - uses: webbertakken/unity-builder@v2.0-aplha-5
        with:
          unityVersion: 2020.2.1f1
          projectPath: Unity
          targetPlatform: StandaloneWindows64
      - uses: actions/upload-artifact@v2.2.1
        with:
          name: Build
          path: build
